### ISSUE TITLE
disk drive doesnt default to /dev/vdX/

### ISSUE THREAD

**Issue by Mekelaina** [fnuecke/oc2#118]
Hey, i was playing witht he mod and ive been having issues witht the disk drives. I cant seem to get them to mount or format a floppy. the guidebook says that they should default to /dev/vdX/ but that doesnt seem to be the case.

 ive attached a screenshot of what mount says when run. 

is the guidebook just out of date (understandable given the mod is still WIP) or is this a bug?

![mount](https://user-images.githubusercontent.com/5855378/152742628-28d0fa59-fea9-4c40-86d6-5f8dcfaffa7b.PNG)

**Comment by Mekelaina** [comment]
and to prove the disc drive is connected.

![lsdev](https://user-images.githubusercontent.com/5855378/152743086-9e6dbc6d-fb9f-4b43-9258-139173b4275b.PNG)

**Comment by fnuecke** [comment]
This may be a little unclear due to assumptions of existing knowledge. If that's the case, I'll try to rephrase the docs. So let's see, since you only showed the output of mount, here's my suspicion of where the misunderstanding lies:
- It is *not* automatically mounted.
- It should show up as `/dev/vdb` e.g. (if there's only one hard drive). So if you do `ls /dev/vd*` you should see it.
- It will be unformatted at first, so you'll need to run `mke2fs` on it.
- So: does `mke2fs /dev/vdb && mkdir /mnt/floppy && mount /dev/vdb /mnt/floppy` work?

**Comment by Mekelaina** [comment]
yes that did wok. sorry about that. thank you for clarifying

**Comment by fnuecke** [comment]
Cool, happy to hear that! Will try to expand on this in the docs, then.
