### ISSUE TITLE
Add intranet for each minecraft world

### ISSUE THREAD

**Issue by getkirill** [fnuecke/oc2#130]
so computers can have internet-like features, so http servers could be useful.

**Comment by spike11302000** [comment]
I was successful in getting [mini_httpd](https://acme.com/software/mini_httpd/) compiled and working for oc2 but i would be nice if there is a built in http server.

I was also successful in getting bgp and ospf working but every hop you make adds 50 ms to the ping because how the networking was implemented.

at some point I may make a repo with a bunch of pre-compiled programs and libraries.

**Comment by man-of-eel** [comment]
> I was successful in getting [mini_httpd](https://acme.com/software/mini_httpd/) compiled and working for oc2 but i would be nice if there is a built in http server.

Busybox has a built-in http server but it isn't enabled in the default image

**Comment by spike11302000** [comment]
> Busybox has a built-in http server but it isn't enabled in the default image

didn't know it had a built in httpd server but it looks like its not enable on the build of busybox oc2 uses

**Comment by fnuecke** [comment]
Unlikely to happen for the default Linux disk, due to disk space. Could be added as a datapack block fs. Even if I were to tackle this myself (which I can't make any promises I'll find the time to), I'd put this in an addon mod, with a bunch of other software. More likely to happen if maintained by someone other than me, though (again, mostly due to lack of time).
