### ISSUE TITLE
Architectury instead of separate branches

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [fnuecke/oc2#158]
Heya, i just looked through the branches and saw how there's a fabric 1.16 and forge 1.16 branch. Seeing as there's things like Architectury which unify your code base, why isn't that used?

**Comment by CoolCat467** [comment]
That is a part of PR #44, but it's super out of date by now.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Ah okay, fair enough aha

**Comment by fnuecke** [comment]
> why isn't that used?

Because it wasn't really ready when I started on this, and I don't have the energy to do porting work. Also I'm relying on capabilities a lot (because I like them, code design-wise), and making this work for Forge and Fabric will probably a major pain. If someone makes a PR for this (and it doesn't make the shared code a pain to maintain) I'd be happy to accept it though!
