### ISSUE TITLE
Two issues:

### ISSUE THREAD

**Issue by Lockl00p** [fnuecke/oc2#159]
First, the file IO card seems like a security hole waiting to be exploited for obvious reasons. If I may suggest, it’s a great idea to remove that feature altogether. 

Second, given the nature of mod developers, I would suggest you create an api for making Linux drivers too as most items that directly affect the Computer, would require a kernel driver and not many can write one, or are willing to learn to. Having to make a kernel driver  may be a turn off for possible plugins. Thanks for taking the time to read this!

**Comment by spike11302000** [comment]
1. The file io card is pretty secured as it requires the user to click on which files to upload and download.
2. there is no need to make a driver for devices because they dont show up as normal devices. you use the HLAPI to interact with external devices using the "/dev/hvc0" device. there is a built in lua library to handle it but there is also use 3rd party libraries like [Coverett](https://github.com/Bs0Dd/Coverett).

**Comment by Lockl00p** [comment]
> * there is no need to make a driver for devices because they dont show up as normal devices. you use the HLAPI to interact with external devices using the "/dev/hvc0" device. there is a built in lua library to handle it but there is also use 3rd party libraries like [Coverett](https://github.com/Bs0Dd/Coverett).

But does the HLAPI work with, for example, a new type of HDD added or a new type of graphics card?

**Comment by spike11302000** [comment]
hdd and other storage devices dont use they HLAPI they just show up as a virtio storage devices so there is no need to write a driver for them and for graphics card im not sure if they will be implemented but if it where to be it would probably use the virtio driver to tell the computer the resolution, color depth, etc

**Comment by fnuecke** [comment]
As mentioned above, since it requires the client to a) currently interact with the computer and b) select a file and hit confirm for anything to happen, I don't really see an attack vector here. If you want to elaborate on the "obvious reasons", I'd be very interested however.

I strongly doubt anyone would want to write actual Linux drivers. Except maybe 0.01% or so. For the majority, as mentioned above, the HLAPI exists. For the rest, the VMDevice API exists, and if anyone actually builds custom devices that need custom drivers (not ones Linux already has drivers for), I'd be easily convinced to enable module loading in the default Linux image, so they can provide their drivers via datapacks.
