### ISSUE TITLE
[Feature request] In-game C compiler

### ISSUE THREAD

**Issue by getItemFromBlock** [fnuecke/oc2#161]
Since the computers emulates Linux, could it be possible to have a gcc-like command, or any way to compile lower-level code?
This may improve execution speed of user-made programs

**Comment by Techokami** [comment]
Isn't GCC kind of heavy? The computers aren't emulating Linux, they are emulating a RISC-V CPU with a minimal embedded Linux system using BusyBox instead of the chufty GNU userland stuff. With a platform like this, what you really should be doing is cross-compiling outside of the game, then sideloading the binaries with one of the higher tier network cards.

**Comment by getItemFromBlock** [comment]
I just realized this was already discussed here  #146 
My bad, I should have looked in the discussions.
Thanks for the reply, I will try to do that for now.

**Comment by fnuecke** [comment]
FTR, I'm looking into making the Tiny C Compiler play nice, but have some remaining segfault issues (which *probably* stems from a bug in my virtual hardware). Hard to debug that though, which is pretty exhausting.
