### ISSUE TITLE
Sound card not playing correctly

### ISSUE THREAD

**Issue by sentwayfarer** [fnuecke/oc2#202]
https://user-images.githubusercontent.com/95097230/169633667-66852db3-b50b-472e-8689-f6b184886fca.mp4

Sound card not playing correctly

**Comment by LaineZ** [comment]
Sound card plays correctly in the reality of Minecraft, and they Sound Engine. Because inside the ``playSound`` sound card method hides the default Minecraft JE ``playSound`` function, for example it's used in ``/playsound`` command. And pitch values above 2.0 will be clamped to 2.0.

https://github.com/fnuecke/oc2/blob/1.18-forge/src/main/java/li/cil/oc2/common/bus/device/rpc/item/SoundCardItemDevice.java#L70

## Here is Minecraft Wiki quote about pitches in /playsound command:

Specifies the pitch of the sound. If not specified, defaults to 1.
    Must be a [Single-precision floating-point format](https://en.wikipedia.org/wiki/Single_precision_floating-point_format) number. In [Java Edition](https://minecraft.fandom.com/wiki/Java_Edition), **it must be between 0.0 and 2.0 (inclusive).**

**Comment by fnuecke** [comment]
I guess it would make sense to either clamp the values or report an error.
