### ISSUE TITLE
Cannot search using less

### ISSUE THREAD

**Issue by superkooks** [fnuecke/oc2#24]
Running `less` then attempting to search for text in the output using `/` does not work. The search term can be entered but the enter key doesn't work, meaning the input can never actually be searched. It also means that you cannot exit less without rebooting.

**Comment by fnuecke** [comment]
The `less` implementation that busybox comes with by default does not support search.
You can still use ctrl+c to quit `less`, no reboot necessary.

Since the rootfs image is almost completely full I'd like to wait to see what other software might potentially be more desirable to add than full featured less. This would pull in `libncurses`, filling up a big chunk of the currently remaining space.

As a workaround for now, open the file you'd like to search in with `vi` and search there.

**Comment by superkooks** [comment]
Ah, didn't try ctrl+c (for some reason). Should I close this issue?

**Comment by fnuecke** [comment]
Feel free to leave it open for now. The Linux image is technically still in flux, so this can serve as a reminder to potentially add full `less`.

In particular with the idea in mind that some other programs may need `libncurses`, too; IIRC `nano` uses that, which would be a more approachable editor for many.

**Comment by fnuecke** [comment]
Was probably an issue with the terminal emulator, works currently.
