### ISSUE TITLE
Including utility scripts

### ISSUE THREAD

**Issue by Emmixis** [fnuecke/oc2#29]
It may be worth including a small multitude of lightweight utilities, akin to the ones seen in distros like DietPi. The Linux image in its current state is, while in flux, limited in usability. Writing in some scripts to make it easier for players to perform otherwise complex tasks would be a treat, as I don't think most players would be at all familiar with using a GNU/Linux system.

It may also be good to look into the possibility of end-users packaging up their own images for running on OC2's implementation of Sedna. (I know this is probably way out of the scope of this issue, but it'd solve the lack of any real usage at-present)

**Comment by Techokami** [comment]
Well this technically isn't a GNU/Linux system. The GNU part means that it is using the GNU utilities with the Linux kernel to create a full OS. However, this system is using BusyBox, an alternative set of utilities that are much more leaner and geared for creating embedded systems with small storage, as the GNU utilities are a bit on the chunky side nowadays, at the cost of not having all the same extended features.

For context, you're looking at DietPi, which is a Debian-based distro. Which means it's using the full-fat GNU utilities. BusyBox, on the other hand, allows for creating [a modern Linux system that fits on a single floppy disk.](https://hackaday.com/2021/05/24/running-modern-linux-from-a-single-floppy-disk/) Since there's going to be quite the opportunity for having loads of data stored within the Minecraft world save in the form of hard disk images, a lighter-weight OS makes the most sense.

**Comment by fnuecke** [comment]
There are some utility scripts now for common tasks, e.g. `lsdev.lua` for listing RPC devices (such as the redstone interface), and one to take you through networking setup (`setup-network.lua`). Will add more as the need arises :)
